version: '3.9'
services:
  mongodb_container:
    container_name: movie-api
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: movie-db
    ports:
      - 27017:27017
